
export const serviceTypes = {
  GET_SERVICE: 'GET_SERVICE',
  GET_SERVICE_SUCCESS: 'GET_SERVICE_SUCCESS',
  ADD_SERVICE: 'ADD_SERVICE',
  ADD_SERVICE_SUCCESS: 'ADD_SERVICE_SUCCESS',
  DELETE_SERVICE: 'DELETE_SERVICE',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
}
